name: LEDMESSENGER
options:
  bundleIdPrefix: com.led.messenger
  deploymentTarget:
    iOS: 16.0
    macOS: 13.0
  xcodeVersion: "15.0"
  groupSortPosition: top

settings:
  base:
    SWIFT_VERSION: 5.0
    DEVELOPMENT_TEAM: "" # Replace with your actual team ID or use ${DEVELOPMENT_TEAM}
    ENABLE_PREVIEWS: YES
    ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentPurple

packages: {}

targets:
  LEDMESSENGER_iPad:
    type: application
    platform: iOS
    sources:
      - path: App
      - path: Models
      - path: ViewModels
      - path: Views
      - path: Services
      - path: Extensions
      - path: Shared
      - path: Utilities
      - path: LEDMESSENGER
        excludes:
          - "**/.DS_Store"
    
    info:
      path: LEDMESSENGER/Info.plist
      properties:
        CFBundleDisplayName: LED MESSENGER
        CFBundleShortVersionString: "1.0"
        CFBundleVersion: "1"
        LSApplicationCategoryType: public.app-category.entertainment
        LSRequiresIPhoneOS: true
        NSLocalNetworkUsageDescription: LED MESSENGER needs to connect to Resolume on your local network to send messages to the LED wall.
        NSBonjourServices: ["_osc._udp"]
        UIStatusBarStyle: UIStatusBarStyleLightContent
        UIViewControllerBasedStatusBarAppearance: false
        UIUserInterfaceStyle: Dark
        UIRequiredDeviceCapabilities: [armv7]
        UISupportedInterfaceOrientations~ipad: [UIInterfaceOrientationPortrait, UIInterfaceOrientationPortraitUpsideDown, UIInterfaceOrientationLandscapeLeft, UIInterfaceOrientationLandscapeRight]
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: true
    
    entitlements:
      path: LEDMESSENGER/LEDMESSENGER.entitlements
      properties:
        com.apple.security.network.client: true
        com.apple.security.network.server: true
        com.apple.security.app-sandbox: true
    
    settings:
      base:
        INFOPLIST_FILE: LEDMESSENGER/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.led.messenger.LEDMESSENGER
        PRODUCT_NAME: LEDMESSENGER_iPad
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        CURRENT_PROJECT_VERSION: 1
        ENABLE_PREVIEWS: YES
        TARGETED_DEVICE_FAMILY: "2"
        
      configs:
        Debug:
          SWIFT_ACTIVE_COMPILATION_CONDITIONS: DEBUG
        Release:
          SWIFT_COMPILATION_MODE: wholemodule
    
    dependencies: []

  LEDMESSENGER_macOS:
    type: application
    platform: macOS
    sources:
      - path: App
      - path: Models
      - path: ViewModels
      - path: Views
      - path: Services
      - path: Extensions
      - path: Shared
      - path: Utilities
      - path: LEDMESSENGER
        excludes:
          - "**/.DS_Store"
    
    info:
      path: LEDMESSENGER/Info.plist
      properties:
        CFBundleDisplayName: LED MESSENGER
        CFBundleShortVersionString: "1.0"
        CFBundleVersion: "1"
        LSApplicationCategoryType: public.app-category.entertainment
    
    entitlements:
      path: LEDMESSENGER/LEDMESSENGER.entitlements
      properties:
        com.apple.security.network.client: true
        com.apple.security.network.server: true
        com.apple.security.app-sandbox: true
    
    settings:
      base:
        INFOPLIST_FILE: LEDMESSENGER/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.led.messenger.LEDMESSENGER
        PRODUCT_NAME: LEDMESSENGER_macOS
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        CURRENT_PROJECT_VERSION: 1
        ENABLE_PREVIEWS: YES
        CODE_SIGN_ALLOW_ENTITLEMENTS_MODIFICATION: YES
        
      configs:
        Debug:
          SWIFT_ACTIVE_COMPILATION_CONDITIONS: DEBUG
        Release:
          SWIFT_COMPILATION_MODE: wholemodule
    
    dependencies: []

  LEDMESSENGERTests_iPad:
    type: bundle.unit-test
    platform: iOS
    deploymentTarget:
      iOS: 16.0
    
    info:
      path: LEDMESSENGERTests/Info.plist
      properties:
        CFBundleDisplayName: LEDMESSENGERTests
        CFBundleShortVersionString: "1.0"
        CFBundleVersion: "1"
    
    sources:
      - path: LEDMESSENGERTests
    
    settings:
      base:
        INFOPLIST_FILE: LEDMESSENGERTests/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.led.messenger.LEDMESSENGERTests
        PRODUCT_NAME: LEDMESSENGERTests_iPad
        TEST_HOST: $(BUILT_PRODUCTS_DIR)/LEDMESSENGER_iPad.app/$(BUNDLE_EXECUTABLE_FOLDER_PATH)/LEDMESSENGER_iPad
    
    dependencies:
      - target: LEDMESSENGER_iPad

  LEDMESSENGERTests_macOS:
    type: bundle.unit-test
    platform: macOS
    deploymentTarget:
      macOS: 13.0
    
    info:
      path: LEDMESSENGERTests/Info.plist
      properties:
        CFBundleDisplayName: LEDMESSENGERTests
        CFBundleShortVersionString: "1.0"
        CFBundleVersion: "1"
    
    sources:
      - path: LEDMESSENGERTests
    
    settings:
      base:
        INFOPLIST_FILE: LEDMESSENGERTests/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.led.messenger.LEDMESSENGERTests
        PRODUCT_NAME: LEDMESSENGERTests_macOS
        TEST_HOST: $(BUILT_PRODUCTS_DIR)/LEDMESSENGER_macOS.app/Contents/MacOS/LEDMESSENGER_macOS
    
    dependencies:
      - target: LEDMESSENGER_macOS

  LEDMESSENGERUITests_iPad:
    type: bundle.ui-testing
    platform: iOS
    deploymentTarget:
      iOS: 16.0
    
    info:
      path: LEDMESSENGERUITests/Info.plist
      properties:
        CFBundleDisplayName: LEDMESSENGERUITests
        CFBundleShortVersionString: "1.0"
        CFBundleVersion: "1"
    
    sources:
      - path: LEDMESSENGERUITests
    
    settings:
      base:
        INFOPLIST_FILE: LEDMESSENGERUITests/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.led.messenger.LEDMESSENGERUITests
        PRODUCT_NAME: LEDMESSENGERUITests_iPad
        TEST_TARGET_NAME: LEDMESSENGER_iPad
    
    dependencies:
      - target: LEDMESSENGER_iPad

  LEDMESSENGERUITests_macOS:
    type: bundle.ui-testing
    platform: macOS
    deploymentTarget:
      macOS: 13.0
    
    info:
      path: LEDMESSENGERUITests/Info.plist
      properties:
        CFBundleDisplayName: LEDMESSENGERUITests
        CFBundleShortVersionString: "1.0"
        CFBundleVersion: "1"
    
    sources:
      - path: LEDMESSENGERUITests
    
    settings:
      base:
        INFOPLIST_FILE: LEDMESSENGERUITests/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.led.messenger.LEDMESSENGERUITests
        PRODUCT_NAME: LEDMESSENGERUITests_macOS
        TEST_TARGET_NAME: LEDMESSENGER_macOS
    
    dependencies:
      - target: LEDMESSENGER_macOS

schemes:
  LEDMESSENGER_iPad:
    build:
      targets:
        LEDMESSENGER_iPad: all
    run:
      config: Debug
      commandLineArguments:
        "-UIPreferredUserInterfaceStyle Dark": true
    test:
      config: Debug
      targets:
        - LEDMESSENGERTests_iPad
        - LEDMESSENGERUITests_iPad
      gatherCoverageData: true
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release

  LEDMESSENGER_macOS:
    build:
      targets:
        LEDMESSENGER_macOS: all
    run:
      config: Debug
      commandLineArguments:
        "-UIPreferredUserInterfaceStyle Dark": true
    test:
      config: Debug
      targets:
        - LEDMESSENGERTests_macOS
        - LEDMESSENGERUITests_macOS
      gatherCoverageData: true
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release